apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-ui-deployment
  labels:
    app: docker-registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-ui
  template:
    metadata:
      labels:
        app: docker-registry-ui
    spec:
      containers:
        - name: docker-registry-ui
          image: dlgmltjr0925/docker-registry-ui:latest
          ports:
            - containerPort: 3000
