apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-web-deployment
  labels:
    app: docker-registry-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-web
  template:
    metadata:
      labels:
        app: docker-registry-web
    spec:
      containers:
        - name: docker-registry-web
          image: dlgmltjr0925/docker-registry-web:latest
          ports:
            - containerPort: 3000
